#page title
page_title                                :                                   # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 6448866508                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : gr                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            : https://play.google.com/store/apps/details?id=com.iraklis.Chargit                                          # Enter Google Play Store URL.
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file).
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon_header                           : assets/appicon-rounded.png
app_icon                                  :                       # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  :                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                         # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Discover EV Chargers

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Iraklis Eleftheriadis
your_link                                 :                      
your_city                                 :                                 
email_address                             : info@oneplug.org
facebook_username                         : oneplugapp                                         
instagram_username                        : oneplug_app
twitter_username                          : oneplugapp
github_username                           : 
youtube_username                          : oneplug_app
mastodon_link                             : 



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Global Data
    description                           : Find EV Chargers from all around the world.
    fontawesome_icon_name                 : globe
    
  - title                                 : Add Locations
    description                           : Add any EV Charging station on the map.
    fontawesome_icon_name                 : plus

  - title                                 : Search
    description                           : Search for any location in the world.
    fontawesome_icon_name                 : search

  - title                                 : Filters
    description                           : Apply filters to show results based on your needs.
    fontawesome_icon_name                 : filter

  - title                                 : Directions
    description                           : Get directions to any EV Charger.
    fontawesome_icon_name                 : road

  - title                                 : Favourites
    description                           : Add any EV Charger to your favourites list for quick access.
    fontawesome_icon_name                 : star

  - title                                 : Leaderboard
    description                           : Contribute to our community and earn points.
    fontawesome_icon_name                 : trophy

  - title                                 : Dark Mode
    description                           : Enjoy our app in dark mode.
    fontawesome_icon_name                 : moon

  - title                                 : Light Mode
    description                           : Enjoy our app in light mode.
    fontawesome_icon_name                 : sun

  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#00A0EA"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.jpg                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.5

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#000000"

link_color                                : "#00A0EA"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#ffffff"
feature_text_color                        : "#808080"

feature_icons_foreground_color            : "#00A0EA"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#00A0EA"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#808080"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME
  
include: [".well-known"]

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
